---
title: Aulia Dika Daily Journal
baseURL: "/"
params:
  layout_style: list
  palette: green
  header:
    title: Ampersand
    logo_img: images/logo.png
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
menu:
  main:
  - url: https://amdevblog.netlify.app/
    name: My DevBlog
    weight: 4
